# Generated by Django 5.2.11 on 2026-03-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Proposal Sent', 'Proposal Sent'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
